/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotesImport } from './routes/notes'
import { Route as AddNoteImport } from './routes/add-note'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NotesRoute = NotesImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRoute,
} as any)

const AddNoteRoute = AddNoteImport.update({
  id: '/add-note',
  path: '/add-note',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add-note': {
      id: '/add-note'
      path: '/add-note'
      fullPath: '/add-note'
      preLoaderRoute: typeof AddNoteImport
      parentRoute: typeof rootRoute
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-note': typeof AddNoteRoute
  '/notes': typeof NotesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-note': typeof AddNoteRoute
  '/notes': typeof NotesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/add-note': typeof AddNoteRoute
  '/notes': typeof NotesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-note' | '/notes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-note' | '/notes'
  id: '__root__' | '/' | '/add-note' | '/notes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddNoteRoute: typeof AddNoteRoute
  NotesRoute: typeof NotesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddNoteRoute: AddNoteRoute,
  NotesRoute: NotesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add-note",
        "/notes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/add-note": {
      "filePath": "add-note.tsx"
    },
    "/notes": {
      "filePath": "notes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
